server:
  port: 8081
spring:
  application:
    name: "CrediYaLoanRequest"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapters:
  r2dbc:
    host: "${DB_HOST}"
    port: 5432
    database: "${DB_NAME}"
    schema: "${DB_SCHEMA}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  restconsumer:
    timeout: 10000
    url: "${ADAPTER_RESTCONSUMER_URL}"
  sqs:
    region: "us-east-2"
    queueUrl: "https://sqs.us-east-2.amazonaws.com/693014165658/notifications-queue"
    queueDebtCapacityUrl: "https://sqs.us-east-2.amazonaws.com/693014165658/debt-capacity-queue"
    endpoint: "http://localhost:4566"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
security:
  jwt:
    secret: "${JWT_SECRET}"
entrypoint:
  sqs:
    region: "us-east-2"
    endpoint: "http://localhost:4566"
    queueUrl: "https://sqs.us-east-2.amazonaws.com/693014165658/sqs_loan_status_update"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
